// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Loot
	{
		public int health;
		public string incHealth;
		public int dmg;

		public void gethealth() {
			health = 10;
			Hero.health+= health;
		}

		public void getIncHealth() {
			Hero.health = Hero.maxhealth;
		}

		public void getDmg() {
			Hero.baseDmg += 10;
		} 
 
		public Loot ()
		{
		}
	}
}

